config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'posts#index'
  resources :posts do
    resources :comments
  end

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { :medium => "640px" }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_presence_of :image, :user_id

  validates :caption, length: { minimum: 3, maximum: 300 }
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :user_name, presence: true, length: { minimum: 4, maximum: 12 }

  has_attached_file :avatar, styles: { medium: '152x152#' }  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path } 
        format.js
      end
    else
      flash.now[:alert] = "Comment was not created, please check the form."
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_path}
        format.js
      end
    end
  end

  def index
    @comments = @post.comments.order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC').page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Your post has been created."
      redirect_to @post
    else
      flash.now[:alert] = "Error: post could not be created, please check the form."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post successfully updated."
      redirect_to(post_path(@post))
    else
      flash.now[:error] = "Error with form inputs."
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    flash[:success] = "Post deleted."
    redirect_to(posts_path)
  end


  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless @post.user.id == current_user.id
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :owned_profile, only: [:edit, :update]
  before_action :set_user

  def show
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      flash[:success] = "Your profile has been updated."
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owner_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Form for post image
  def form_image_select(post)
    return image_tag post.image.url(:medium),
                     id: 'image-preview',
                     class: 'img-responsive' if post.image.exists?
    image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive'
  end

  # Profile Avatar
  def profile_avatar_select(user)
    return image_tag user.avatar.url(:medium),
                    id: 'image-preview',
                    class: 'img-responsive img-circle profile-image' if user
  .avatar.exists?
    image_tag 'default-avatar.png', id: 'image-preview',
                                    class: 'img-responsive img-circle profile-image'
  end


  # Alert flash types
  def alert_for(flash_type)
    case flash_type
      when :success
        "alert-success"   # Green
      when :error
        "alert-danger"    # Red
      when :alert
        "alert-warning"   # Yellow
      when :notice
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.erb
<div class="user-name">
  <%= link_to comment.user.user_name, profile_path(comment.user.user_name) %>
</div>
<div class="comment-content">
  <%= comment.content %>
</div>
<% if comment.user == current_user %>
  <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
    <span class="glyphicon glyphicon-remove delete-comment"></span>
  <% end %>
<% end %>
</br>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post:
  @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('');

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%=j render @post.comments, post: 
  @post, comment: @comment %>");

app/views/comments/index.html.erb
<%= render @comments, post: @post %>

app/views/layouts/_messages.html.erb
<div class="container" id="flash-errors">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
          <li>
            <%= value %>
          </li>
        </ul>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="cantainer-fluid navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon_bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Photogram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Logout (#{current_user.user_name})", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <%= render "layouts/messages" %>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_image_select(@post) %>
        <%= form_for @post, html: { class: 'form-horizontal' } do |f|  %>
          <div class="row">
            <div class="col-md-12 text-center">
              <!-- add errors -->
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image (this is required):</h4>
              <%= f.file_field :image, onchange: 'loadFile(event)' %>
            </div>
            <div class="form-group text-center">
              <%= f.text_field :caption, placeholder: "Add your caption" %>
            </div>
            <div class="form-group text-center">
              <%= f.submit "Submit", class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
      </div>
      <div class="time-ago">
        <%= time_ago_in_words post.created_at %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="caption">
        <div class="caption-content">
          <div class="user-name">
            <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
          </div>
          <%= post.caption %>
        </div>
        <div class="comments" id="comments_<%= post.id %>">
          <% if post.comments.any? %>
            <div class="paginator" id="comments-paginator-<%= post.id %>">
              <% unless post.comments.count <= 4 %>
                <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: { post_id: "#{post.id}", type: "html"} %>
              <% end %>
            </div>
            <%= render post.comments.last(4), post: post %>
          <% end %>
        </div>
        <div class="comment-like-form row">
          <div class="like-button col-sm-1">
            <span class="glyphicon glyphicon-heart-empty"></span>
          </div>
          <div class="comment-form col-sm-11">
            <%= form_for([post, post.comments.build], remote: true) do |f| %>
              <%= f.text_field :content, placeholder: 'Add a comment...', class:"comment_content", id: "comment_content_#{post.id}" %>
              <%= f.submit 'Submit', class: 'comment-submit-button' %><!-- Hidden with CSS -->
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<div class="posts-wrapper row">
  <% @posts.each do |post|%>
    <%= render 'post', post: post %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render "form"  %>

<div class="text-center edit-links">
  <%= link_to "Delete", post_path(@post), method: "Delete", data: { confirm: "Are your sure you want to delete this post" } %>
  |
  <%= link_to "Cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<div id="posts">
  <%= render 'posts' %>
</div>
<div class="text-center" id='paginator'>
  <%= link_to_next_page @posts, "LOAD MORE", remote: true, id: 'load_more' %>
<div>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 
                      'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); };  

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"} do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.user_name %>
        </h3>
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), 
                                        class: "btn edit-button" %>
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <p>
          <%= pluralize @user.posts.count, 'post' %>
        </p>
      </div>
    </div>
  </div>
</div>


<div class="posts-wrapper row">
  <% @posts.each do |post|%>
    <%= render 'posts/post', post: post %>
  <% end %>
</div>